{
  parserUtilClass="aldor.list.ListParserUtil"

  parserClass="aldor.list.ListParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  elementTypeHolderClass="aldor.list.ListTypes"
  elementTypeClass="aldor.list.ListElementType"

  tokenTypeClass="aldor.list.ListTokenType"
  tokenTypeFactory = "aldor.list.ListTokenTypes.createToken"

  psiClassPrefix="List"
  psiImplClassSuffix="Impl"
  psiPackage="aldor.list.psi"
  psiImplPackage="aldor.list.impl"

  tokens = [ OP CP OSQ CSQ E Sep ]

}

Goal ::= OP enlist1a CP | OSQ enlist1 CSQ | enlist2

enlist2 ::= enlister1 Sep E
enlist1 ::= enlister1
//enlister1 ::= E | enlister1 Sep E
enlister1 ::= E (Sep E)*

enlist1a ::= enlister1a

//enlister1a ::= E | enlister1a Sep E | enlister1a Sep
enlister1a ::= E (Sep E)* Sep?

