name: Java CI

on: [push]

env:
  GITHUB_REF: ${{ github.ref }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Create mini-script
      run: echo "wrapper {gradleVersion='5.2.1'}" > nada.gradle
    - name: Create Wrapper
      run: gradle -b nada.gradle wrapper
    - name: Check version
      run: ./gradlew --version
    - name: Build
      run: ./gradlew assemble

    - name: Test
      run: ./gradlew check -Daldor.build.skip_ci=true --continue

    - name: Publish Test Results
      if: ${{ always() }}
      uses: mikepenz/action-junit-report@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        report_paths: '**/test-results/test/TEST-*.xml'
